version: "3"

services:
  jobs:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    container_name: jobs
    command: >
      sh -c " cd jobs &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
