# Generated by Django 3.1.7 on 2021-03-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_jobs', '0002_auto_20210321_1359'),
        ('condidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondidateJobMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('condidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condidates.condidate')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_jobs.newjob')),
            ],
        ),
    ]
