# Generated by Django 3.1.7 on 2021-03-21 13:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewJobs',
            new_name='NewJob',
        ),
        migrations.RenameField(
            model_name='newjob',
            old_name='create',
            new_name='creator',
        ),
    ]
